### ISSUE TITLE
Error in refresh monitored downloads and never recovered

### ISSUE THREAD

**Issue by ImjuzCY** [linuxserver/docker-radarr#100]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

My setup: linuxserver/radarr:preview on a VPS, connected to two download clients (NZBGet and rTorrent) on another seedbox. Once the Radarr container is restarted, it'll work fine for like an hour, and then it'll have errors connecting to both of the clients and never recover from it. The Refresh Monitored Downloads and sometimes Processing Monitored Downlaods tasks will be running forever. [Screenshot]( https://preview.redd.it/k52rv0lnikc51.png?width=1612&format=png&auto=webp&s=0ade52ea92707d99312e2370acdb3ced7478dbd3)

------------------------------

## Expected Behavior
After the error it should just stop the task, and run again the next time.

## Current Behavior
After the error, the task will just go on forever and never ends, hence it'll not try again.

## Steps to Reproduce
1. Start container linuxserver/radarr:preview
2. Run download clients on another seedbox
3. Connect Radarr and Download Clients via https
4. Wait for a error when Radarr tries to refresh monitored downloads

## Environment
**OS:**      Ubuntu 20.04
**CPU architecture:** x86_64      
**How docker service was installed:**      With official guide on Docker's website

## Command used to create docker container (run/create/compose/screenshot)
```
  radarr-x264:
    image: linuxserver/radarr:preview
    container_name: radarr-x264
    depends_on:
      - unionfs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
    volumes:
      - /home/docker/radarr-x264/config:/config
      - /mnt/gdrive-unionfs/movies/AVC:/movies:shared
    restart: unless-stopped
    healthcheck:
      test: ls /movies > /dev/null
      timeout: 120s
```

## Docker logs
Unable to retrieve queue and history items from NZBGet - seedbox: Unable to connect to NzbGet. The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.: 'https://seedbox/nzbget/jsonrpc' 
```
NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to NzbGet. The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.: 'https://seedbox/nzbget/jsonrpc'
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.: 'https://seedbox/nzbget/jsonrpc'
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 145
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 145
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 61
   at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T](NzbgetSettings settings, String method, Object[] parameters) in d:\a\1\s\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:line 252
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T](NzbgetSettings settings, String method, Object[] parameters) in d:\a\1\s\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:line 252
   at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetQueue() in d:\a\1\s\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:line 59
   at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetItems() in d:\a\1\s\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:line 188
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in d:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 89
```

Unable to retrieve queue and history items from rTorrent - seedbox: The operation was canceled.
```
System.OperationCanceledException: The operation was canceled.
   at System.Net.HttpWebRequest.GetResponse()
   at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse(WebRequest request)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   at XmlRpcProxye8e3e77b-fcc6-4672-bcff-07a0f02e8788.TorrentMulticall(String[] parameters)
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T](Func`1 task) in d:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 267
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetTorrents(RTorrentSettings settings) in d:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 76
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.GetItems() in d:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:line 106
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in d:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 89
```

**Comment by hotio** [comment]
This is for issues with the container, not for support with faulty setups/configuration.

`The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.`

This should give you an idea on where to look.
