### ISSUE TITLE
[BUG] Synology download station hostname is not being resolved

### ISSUE THREAD

**Issue by bobvmierlo** [linuxserver/docker-radarr#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Radarr can't resolve my FQDN for Synology DS. Using the exact same settings in Sonarr without any issues.

### Steps To Reproduce

Trying to change the host to my new download station subdomain, Radarr can't resolve the Synology DS.

### Environment

```markdown
- OS: Synology DSM 7.2
- How docker service was installed: As a docker container connected to the default bridge network
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=101
      - PGID=1026
      - TZ=Europe/Amsterdam
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/video/Films:/movies #optional
      - /volume1/video/Processing:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
```

### Container logs

```bash
[Error] TorrentDownloadStation: Error testing Torrent Download Station 

[v4.6.4.7568] System.Net.Http.HttpRequestException: Name does not resolve (download.REDACTED.COM:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.attemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 296
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.onConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 272
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in ./Radarr.Common/Http/HttpClient.cs:line 141
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs:line 81
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.UpdateApiInfo(DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs:line 220
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo(DiskStationApi api, DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs:line 247
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo(DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs:line 268
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxyV2.IsApiSupported(DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs:line 25
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxySelector.FetchProxy(DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxySelector.cs:line 53
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxySelector.<>c__DisplayClass6_0.<GetProxyCache>b__0() in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxySelector.cs:line 48
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Radarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxySelector.GetProxyCache(DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxySelector.cs:line 48
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxySelector.GetProxy(DownloadStationSettings settings) in ./Radarr.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxySelector.cs:line 41
   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.get_DsTaskProxy() in ./Radarr.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs:line 55
   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.ValidateVersion() in ./Radarr.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs:line 400
   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.TestConnection() in ./Radarr.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs:line 363


[Warn] RadarrErrorPipeline: Invalid request Validation failed: 
 -- Host: Unable to connect to Torrent Download Station
```

**Comment by drizuid** [comment]
1) comparing sonarr and radarr does not make sense, they are different projects. 
2) we do not control your DNS
3) we support the container, not the application within the container. radarr has its own support, though this is more likely a host issue.
4) My radarr container is able to resolve everything on my network, implying this is a host issue on your side (see bullet 2)
