### ISSUE TITLE
[BUG] Constant Failed to get runtime from the file, make sure ffprobe is available

### ISSUE THREAD

**Issue by ren-del** [linuxserver/docker-radarr#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

These errors are constant on my setup, multiple ffprobe unavailable and errors on VIDEO_TS folders

 - Failed to get runtime from the file, make sure ffprobe is available

 - Unable to parse media info from file: /PATH)/VIDEO_TS/VIDEO_TS.IFO: ffprobe exited with non-zero exit-code (1 - /PATH/VIDEO_TS/VIDEO_TS.IFO: Invalid data found when processing input)

- FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /PATH/VIDEO_TS/VIDEO_TS.IFO: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

### Expected Behavior

No error

### Steps To Reproduce

1. Download a DVD-R or other file it cant parse with ffprobe
2. Shows error in logs

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /plex/docker/radarr:/config
      - /Media:/Media
      - /rtorrent/download:/rtorrent/download
    ports:
      - 7878:7878
    restart: unless-stopped
```

### Container logs

```bash
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] VideoFileInfoReader: Unable to parse media info from file: /Path/VIDEO_TS/VIDEO_TS.IFO

[v5.1.3.8246] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /Path/VIDEO_TS/VIDEO_TS.IFO: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140


[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] VideoFileInfoReader: Unable to parse media info from file: /Path/VIDEO_TS/VTS_01_0.IFO

[v5.1.3.8246] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /PATH/VIDEO_TS/VTS_01_0.IFO: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Radarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140


[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] DetectSample: Failed to get runtime from the file, make sure ffprobe is available
[Error] VideoFileInfoReader: Unable to parse media info from file: /PATH/VIDEO_TS/VIDEO_TS.IFO
```

**Comment by TimDowker** [comment]
Same error for me.

**Comment by trevordavies095** [comment]
Also running into this issue

**Comment by homerr** [comment]
Appears to be an issue specific to radarr - please work on this with them.

**Comment by xacobemr** [comment]
Same issue here
