### ISSUE TITLE
[BUG] Searching for any movie fails. Invalid response received from RadarrAPI. 

### ISSUE THREAD

**Issue by g1uliano** [linuxserver/docker-radarr#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error occurs: "Search for '' failed. Invalid response received from RadarrAPI."

Additional Information

The error occurs while trying to fetch an image from image.tmdb.org:443. It seems that the resource is temporarily unavailable, causing the search to fail for any movie.

I have checked the Pi-hole DNS resolver, and all requests are fine. I also changed the DNS on the host machine to 1.1.1.1 and 8.8.8.8, but the problem persists. Accessing the API directly via the browser (https://image.tmdb.org/) returns a "Bad request" error, indicating that the request might be incorrect but the connection to the HTTPS server is being closed.

I don't believe is a network issue in my side, i ran a lot of tests.

### Expected Behavior

The searched movie should be found and listed.

### Steps To Reproduce

   - Open Radarr.
   - Go to the search field.
   - Search for any movie (e.g., 'The Garfield Movie').

### Environment

```markdown
- OS: Manjaro rolling stable
- Radarr: 5.6.0.8846 (5.6.0.8846-ls219) from [linuxserver.io](https://linuxserver.io/)
- NET:   Yes (6.0.29)
- Database:  Sqlite 3.44.2
- Database migration:   236
- AppData Directory:  /config
- Startup Directory: /app/radarr/bin
- Mode:  Console
- Docker Install: Version: 25.0.3
- Using Reverse Proxy: Nginx Proxy Manager
- Browser: Firefox 125.0.1
- Docker Image: lscr.io/linuxserver/radarr:latest
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker run -d 
 --name=radarr 
  -e PUID=1000 
  -e PGID=1000 
  -e TZ=America/Rio_Branco 
  -p 7878:7878 
  -v /storage/config/radarr:/config 
  -v /storage/movies:/movies 
  -v /storage/downloads:/downloads 
  --restart always 
  lscr.io/linuxserver/radarr:latest\	59s
```

### Container logs

```bash
[Fatal] RadarrErrorPipeline: Request Failed. GET /MediaCoverProxy/7d0f1a0a0a793161319bfa3750b44a99d6c403cb92ce2e5f0dd11d0acc38d652/OHGtRqIim2cEHOYKPlbgNOV6Cb.jpg

[v5.6.0.8846] System.Net.Http.HttpRequestException: Resource temporarily unavailable (image.tmdb.org:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.attemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 337
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.onConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 313
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Radarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 115
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Radarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.MediaCover.MediaCoverProxy.GetImage(String hash) in ./Radarr.Core/MediaCover/MediaCoverProxy.cs:line 67
   at Radarr.Http.Frontend.Mappers.MediaCoverProxyMapper.GetResponse(String resourceUrl) in ./Radarr.Http/Frontend/Mappers/MediaCoverProxyMapper.cs:line 46
   at Radarr.Http.Frontend.StaticResourceController.MapResource(String path) in ./Radarr.Http/Frontend/StaticResourceController.cs:line 75
   at Radarr.Http.Frontend.StaticResourceController.Index(String path) in ./Radarr.Http/Frontend/StaticResourceController.cs:line 47
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by Tonynks** [comment]
I'm having this same exact issue.  What I'm finding is the communication with prowlarr is failing all my linked indexers.  However if I go-to prowlarr all the indexers show green health.  Only in radarr and sonarr does it show failure.

**Comment by j0nnymoe** [comment]
You need to seek support from radarr directly.

**Comment by FrederikSchack** [comment]
Ok, seems like something happened between AdGuardHome and the Docker DNS. I changed the /etc/resolv.conf in the host to 1.1.1.1 and it works, but not with AdGuard even if protection is turned off and there's nothing in the AdGuard log that indicats that anything was blocked.

**Comment by lavcanskiz** [comment]
I do not have AdGuardHome and still get the following errors:

All search-capable indexers are temporarily unavailable due to recent indexer errors
All rss-capable indexers are temporarily unavailable due to recent indexer errors
All indexers are unavailable due to failures for more than 6 hours

**Comment by smorello87** [comment]
> I do not have AdGuardHome and still get the following errors:
> 
> All search-capable indexers are temporarily unavailable due to recent indexer errors All rss-capable indexers are temporarily unavailable due to recent indexer errors All indexers are unavailable due to failures for more than 6 hours

+1

**Comment by taslabs-net** [comment]
Same issue just popped up on mine as well.
