### ISSUE TITLE
[BUG] Unable to open database file unable to open database file

### ISSUE THREAD

**Issue by codeuriii** [linuxserver/docker-radarr#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I reload radarr after request a movie with overseer and it show "unable to open database file unable to open database file Version 5.0.0.7836" i'm using docker.

### Steps To Reproduce

Config overseerr and radarr
Request movie who is not already in radarr
Reload localhost:7878
See error
Restart container
See logs

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: Docker desktop from snap store
```

### CPU architecture

x86-64

### Docker creation

```bash
I'm using docker desktop
```

### Container logs

```bash
2024-06-09 10:59:35 chown: changing ownership of '/config/radarr.db-shm': No such file or directory
2024-06-09 10:59:35 **** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
2024-06-09 10:59:35 **** The app may not work properly and we will not provide support for it. ****
2024-06-09 10:59:35 [custom-init] No custom files found, skipping...
2024-06-09 10:59:36 [Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 5.0.0.7836 
2024-06-09 10:59:36 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-06-09 10:59:36 [Debug] Bootstrap: Console selected 
2024-06-09 10:59:36 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-06-09 10:59:36 [Info] AppFolderInfo: Data directory is being overridden to [/config] 
2024-06-09 10:59:37 [Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
2024-06-09 10:59:37 [Fatal] Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception 
2024-06-09 10:59:37 
2024-06-09 10:59:37 [v5.0.0.7836] NzbDrone.Core.Datastore.CorruptDatabaseException: Radarr failed to start: Database file: code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x87AF03F3): unable to open database file
2024-06-09 10:59:37 unable to open database file
2024-06-09 10:59:37    at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteDataReader.NextResult()
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteConnection.Open()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.GenericProcessorBase.<>c__DisplayClass6_1.<.ctor>b__1()
2024-06-09 10:59:37    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2024-06-09 10:59:37    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2024-06-09 10:59:37    at System.Lazy`1.CreateValue()
2024-06-09 10:59:37    at System.Lazy`1.get_Value()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.GenericProcessorBase.get_Connection()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsOpen()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Exists(String template, Object[] args)
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.TableExists(String schemaName, String tableName)
2024-06-09 10:59:37    at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable()
2024-06-09 10:59:37    at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
2024-06-09 10:59:37    at FluentMigrator.Runner.VersionLoader..ctor(IProcessorAccessor processorAccessor, IConventionSet conventionSet, IMigrationRunnerConventions conventions, IVersionTableMetaData versionTableMetaData, IMigrationRunner runner)
2024-06-09 10:59:37    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2024-06-09 10:59:37    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.FluentMigratorServiceCollectionExtensions.<>c.<AddFluentMigratorCore>b__0_6(IServiceProvider sp)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2024-06-09 10:59:37    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2024-06-09 10:59:37    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2024-06-09 10:59:37    at System.Lazy`1.CreateValue()
2024-06-09 10:59:37    at System.Lazy`1.get_Value()
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.get_VersionLoader()
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.IsMigrationStepNeededForUpMigration(IMigrationInfo migration, Int64 targetVersion)
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass60_0.<GetUpMigrationsToApply>b__0(KeyValuePair`2 pair)
2024-06-09 10:59:37    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.MigrateUp()
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/Migration/Framework/MigrationController.cs:line 79
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 115 is corrupt, restore from backup if available. See: https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 126
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 70
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in ./Radarr.Core/Datastore/DbFactory.cs:line 58
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in ./Radarr.Core/Datastore/Extensions/CompositionExtensions.cs:line 10
2024-06-09 10:59:37    at DryIoc.Registrator.ToFuncWithObjParams[D1,TService](Func`2 f, Object d1) in /_/src/DryIoc/Container.cs:line 7977
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretFuncInvoke(IResolverContext r, MethodCallExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3680
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3478
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3129
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3058
2024-06-09 10:59:37    at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11017
2024-06-09 10:59:37    at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10936
2024-06-09 10:59:37    at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 535
2024-06-09 10:59:37    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 463
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3614
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3141
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs) in /_/src/DryIoc/Container.cs:line 3424
2024-06-09 10:59:37    at DryIoc.Interpreter.<>c__DisplayClass5_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3323
2024-06-09 10:59:37    at DryIoc.Interpreter.<>c__DisplayClass9_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3434
2024-06-09 10:59:37    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2024-06-09 10:59:37    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2024-06-09 10:59:37    at System.Lazy`1.CreateValue()
2024-06-09 10:59:37    at System.Lazy`1.get_Value()
2024-06-09 10:59:37    at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, RadarrErrorPipeline errorHandler) in ./Radarr.Host/Startup.cs:line 236
2024-06-09 10:59:37    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2024-06-09 10:59:37    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2024-06-09 10:59:37 
2024-06-09 10:59:37 
2024-06-09 10:59:37 
2024-06-09 10:59:37 
2024-06-09 10:59:37 [Fatal] ConsoleApp: EPIC FAIL! 
2024-06-09 10:59:37 
2024-06-09 10:59:37 [v5.0.0.7836] NzbDrone.Core.Datastore.CorruptDatabaseException: Radarr failed to start: Database file: code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x87AF03F3): unable to open database file
2024-06-09 10:59:37 unable to open database file
2024-06-09 10:59:37    at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteDataReader.NextResult()
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
2024-06-09 10:59:37    at System.Data.SQLite.SQLiteConnection.Open()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.GenericProcessorBase.<>c__DisplayClass6_1.<.ctor>b__1()
2024-06-09 10:59:37    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2024-06-09 10:59:37    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2024-06-09 10:59:37    at System.Lazy`1.CreateValue()
2024-06-09 10:59:37    at System.Lazy`1.get_Value()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.GenericProcessorBase.get_Connection()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsOpen()
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Exists(String template, Object[] args)
2024-06-09 10:59:37    at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.TableExists(String schemaName, String tableName)
2024-06-09 10:59:37    at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable()
2024-06-09 10:59:37    at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
2024-06-09 10:59:37    at FluentMigrator.Runner.VersionLoader..ctor(IProcessorAccessor processorAccessor, IConventionSet conventionSet, IMigrationRunnerConventions conventions, IVersionTableMetaData versionTableMetaData, IMigrationRunner runner)
2024-06-09 10:59:37    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2024-06-09 10:59:37    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.FluentMigratorServiceCollectionExtensions.<>c.<AddFluentMigratorCore>b__0_6(IServiceProvider sp)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2024-06-09 10:59:37    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2024-06-09 10:59:37    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2024-06-09 10:59:37    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2024-06-09 10:59:37    at System.Lazy`1.CreateValue()
2024-06-09 10:59:37    at System.Lazy`1.get_Value()
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.get_VersionLoader()
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.IsMigrationStepNeededForUpMigration(IMigrationInfo migration, Int64 targetVersion)
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass60_0.<GetUpMigrationsToApply>b__0(KeyValuePair`2 pair)
2024-06-09 10:59:37    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
2024-06-09 10:59:37    at FluentMigrator.Runner.MigrationRunner.MigrateUp()
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/Migration/Framework/MigrationController.cs:line 79
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 115 is corrupt, restore from backup if available. See: https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 126
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in ./Radarr.Core/Datastore/DbFactory.cs:line 70
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in ./Radarr.Core/Datastore/DbFactory.cs:line 58
2024-06-09 10:59:37    at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in ./Radarr.Core/Datastore/Extensions/CompositionExtensions.cs:line 10
2024-06-09 10:59:37    at DryIoc.Registrator.ToFuncWithObjParams[D1,TService](Func`2 f, Object d1) in /_/src/DryIoc/Container.cs:line 7977
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretFuncInvoke(IResolverContext r, MethodCallExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3680
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3478
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3129
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3058
2024-06-09 10:59:37    at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11017
2024-06-09 10:59:37    at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10936
2024-06-09 10:59:37    at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 535
2024-06-09 10:59:37    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 463
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3614
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3141
2024-06-09 10:59:37    at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs) in /_/src/DryIoc/Container.cs:line 3424
2024-06-09 10:59:37    at DryIoc.Interpreter.<>c__DisplayClass5_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3323
2024-06-09 10:59:37    at DryIoc.Interpreter.<>c__DisplayClass9_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3434
2024-06-09 10:59:37    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2024-06-09 10:59:37    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2024-06-09 10:59:37    at System.Lazy`1.CreateValue()
2024-06-09 10:59:37    at System.Lazy`1.get_Value()
2024-06-09 10:59:37    at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, RadarrErrorPipeline errorHandler) in ./Radarr.Host/Startup.cs:line 236
2024-06-09 10:59:37    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2024-06-09 10:59:37    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
2024-06-09 10:59:37    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2024-06-09 10:59:37    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2024-06-09 10:59:37    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2024-06-09 10:59:37    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2024-06-09 10:59:37    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2024-06-09 10:59:37    at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Radarr.Host/Bootstrap.cs:line 78
2024-06-09 10:59:37    at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Radarr.Console/ConsoleApp.cs:line 43
2024-06-09 10:59:37 
2024-06-09 10:59:37 
2024-06-09 10:59:37 Press enter to exit...
2024-06-09 10:59:38 Non-recoverable failure, waiting for user intervention...
```

**Comment by j0nnymoe** [comment]
We do not support/test in docker desktop. Please switch to docker-engine.
