### ISSUE TITLE
Moving files fails on preview

### ISSUE THREAD

**Issue by martimarkov** [linuxserver/docker-radarr#76]
## Expected Behavior
Uploads should work. 

## Current Behavior
Upload fails after completed or manual import has been initiated. 
Also, another issue which might be related is Radarr/Radarr/issues/3908

## Environment
**OS:** Unraid 6.7.3-rc4
**CPU architecture:** arm64      
**How docker service was installed:** Part of Unraid

## Command used to create docker container (run/create/compose/screenshot)

<img width="1167" alt="Screenshot 2019-12-30 at 18 14 48" src="https://user-images.githubusercontent.com/1858736/71590420-0675d980-2b31-11ea-9764-74e444167eb5.png">

## Docker logs

```
root@Tardis:~# docker logs Radarr
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-warning: executing... 

******************************************************
******************************************************
*                                                    *
*                                                    *
*         This image is for development only         *
*                                                    *
*              Use at your own peril                 *
* It will likely have bugs and not function properly *
*                                                    *
*                                                    *
******************************************************
******************************************************
[cont-init.d] 90-warning: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Radarr - /opt/radarr/Radarr.dll - Version 3.0.0.2423 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] Router: Application mode: Interactive 
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLoggerProvider: *** 162: fix_profile_format_default migrating *** 
[Info] fix_profile_format_default: Starting migration to 162 
[Info] MigrationLoggerProvider: *** 163: task_duration migrating *** 
[Info] task_duration: Starting migration to 163 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLoggerProvider: *** 162: fix_profile_format_default migrating *** 
[Info] fix_profile_format_default: Starting migration to 162 
[Info] MigrationLoggerProvider: *** 163: task_duration migrating *** 
[Info] task_duration: Starting migration to 163 
[Info] WebHostController: Listening on the following URLs: 
[Info] WebHostController:   http://*:7878 
[Info] RadarrBootstrapper: Starting Web Server 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] RssSyncService: Starting RSS Sync 
[Info] PreDBService: Starting PreDB Sync 
[Info] NetImportSearchService: Found 13 movies on your auto enabled lists not in your library 
[Info] DownloadDecisionMaker: Processing 100 releases 
[Info] RssSyncService: RSS Sync Completed. Reports found: 100, Reports grabbed: 0 
[Warn] ImportApprovedMovie: Couldn't import movie /downloads/Song.of.the.Sea.2014.1080p.BluRay.x264.DTS-HD.MA.5.1-RARBG/Song.of.the.Sea.2014.1080p.BluRay.x264.DTS-HD.MA.5.1-RARBG.mkv 

[v3.0.0.2423] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified)
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode)
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

[Warn] ImportApprovedMovie: Couldn't import movie /downloads/Le.Samourai.1967.1080p.BluRay.x264-PSYCHD[rarbg]/Le.Samourai.1967.1080p.BluRay.x264-PSYCHD.mkv 

[v3.0.0.2423] System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified)
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode)
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)
```

**Comment by thelamer** [comment]
Ignores warning in logs that preview is unsupported

Proceeds to ignore issue template on GitHub that says this is not the platform for support

**Comment by martimarkov** [comment]
It's fine that there might be bugs but this used to work so I think it might be a regression from a previous build. Again there was no update for Radarr when this stopped working so I think it might be some of the base images that caused the issue with permissions. 

Do you think this is something worth investigating @thelamer ?
